### ISSUE TITLE
Cannot create a string longer than 0x1fffffe8 characters

### ISSUE THREAD

**Issue by cryptowhizzard** [tech-greedy/singularity#135]
2022-08-27T17:50:19.430Z [deal_tracking_service] info: Start update deal tracking - {}
node:buffer:594
    slice: (buf, start, end) => buf.utf8Slice(start, end),
                                    ^

Error: Cannot create a string longer than 0x1fffffe8 characters
    at Buffer.utf8Slice (<anonymous>)
    at Object.slice (node:buffer:594:37)
    at Buffer.toString (node:buffer:812:14)
    at joinChunks (/root/singularity/node_modules/promisify-child-process/index.cjs:25:33)
    at defineOutputs (/root/singularity/node_modules/promisify-child-process/index.cjs:81:24)
    at ChildProcess.done (/root/singularity/node_modules/promisify-child-process/index.cjs:112:9)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5) {
  code: 'ERR_STRING_TOO_LONG'
}
2022-08-27T18:00:19.441Z [deal_tracking_service] info: Start update deal tracking - {}
2022-08-27T18:10:19.449Z [deal_tracking_service] info: Start update deal tracking - {}

**Comment by xinaxu** [comment]
this and #121 seem to be related to the stdin and stdout piping between node and golang. We need to parse the stream chunk by chunk instead of handling it with a large string.
