### ISSUE TITLE
Singularity-retrieve is broken

### ISSUE THREAD

**Issue by marshyonline** [tech-greedy/singularity#166]
**Describe the bug**
```
~/fce001# singularity-retrieve cp singularity://ipns/fce001.vc.distributedstorage.com/2017/November/'HL1 cells'/HL1__FITC_CY5_20171121123830 /root/fce001/ --ipfs-api http://100.110.7.51:5001/ --provider f01919423
**SNIP LOUTS REC DATA**
ERROR: mkdir /root/fce001/.fetching/HL1__FITC_CY5_20171121123830: no such file or directory

/root/.nvm/versions/node/v16.16.0/lib/node_modules/@techgreedy/singularity/dist/src/retrieval/Retrieval.js:152
                    console.error(retrieveResult.stderr.toString());
                                                        ^

TypeError: Cannot read properties of null (reading 'toString')
    at Function.cp (/root/.nvm/versions/node/v16.16.0/lib/node_modules/@techgreedy/singularity/dist/src/retrieval/Retrieval.js:152:57)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Command.<anonymous> (/root/.nvm/versions/node/v16.16.0/lib/node_modules/@techgreedy/singularity/dist/src/singularity-retrieve.js:46:5)
```

**Version**
`2.0.0`

**To Reproduce**
Run Command Above

**Expected behavior**
Folder/File is reterived.

**Comment by xinaxu** [comment]
Fixed in #170
